### ISSUE TITLE
latest sysbench package is broken (1.0.10)

### ISSUE THREAD

**Issue by Reiner030** [percona/sysbench-packaging#2]
Perhaps not the full correct place to notify this bug but since there seems no public support/contact address for Percona tool packages it seems best fitting alternative.

While trying to test lua based version from your package I always got
```
# sysbench
Illegal instruction
```
and thought first thats my fault by missing e.g. parameters. 
But testing with strace shows that this is a binary problem:

```
# uname -a
Linux test-vm 4.9.0-0.bpo.4-amd64 #1 SMP Debian 4.9.51-1~bpo8+1 (2017-10-17) x86_64 GNU/Linux
# sysbench --version
sysbench 1.0.10
# strace sysbench threads help
...
set_tid_address(0x7fd687dfcb50)         = 19167
set_robust_list(0x7fd687dfcb60, 24)     = 0
rt_sigaction(SIGRTMIN, {0x7fd68742d9b0, [], SA_RESTORER|SA_SIGINFO, 0x7fd687436890}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7fd68742da40, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7fd687436890}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
brk(0)                                  = 0x2605000
brk(0x2626000)                          = 0x2626000
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPN, si_addr=0x410657} ---
+++ killed by SIGILL +++
Illegal instruction
```
Would be nice if could be fixed within next release of 1.0.11 which is already out since some days ;)
Bests

**Comment by EvgeniyPatlan** [comment]
Hi I could not reproduce this issue. Could you please provide some more details how it could be reproduced?

**Comment by Reiner030** [comment]
Hello,
mmh. good question what could be different; we are running 
* latest Debian Jessie 8.10 with additional backports (kernel; ssl libraries, etc.
* using MariaDB client/server: `mariadb-client-core-10.1: /usr/bin/mysql`
* .... ah, it's running    (other packages/settings should be same setup by saltstack)
  * fine in real hardware, 
  * fine in AWS Xen hypervisor
  * but not in our VMware ESXi 5.5U3 based test VM
    (newer version not possible because of "unsupported CPU" :disappointed: )

Sorry, then this bug is more informational that it may have problems
